### PR TITLE
add new tooctl command to export domain block list (#316)

### PR DESCRIPTION
**Pull request by Mansh05**
command: bin/tootctl domains:export_blocked <url>

Need testing on a real time senario.

### CODE REVIEW

**Comment by weex** [comment]
Hey @Mansh05, I noticed this POSTs the file to a remote location but the issue there is that a third party needs to run an API to accept the file, then make it publicly accessible. Do you mind adding a switch to have it save the file locally? See my proposed solution in #316. Let me know what you think.

**Comment by weex** [comment]
The difference is whether this PR is enough to enable full automation or not.

**Comment by Mansh05** [comment]
@weex, I understood the pain point here.

The things that i had in mind here was exporting the domains to publicly exposed api rather than a site. What i thought here was some sites will open up their apis to accept the list that we export here.

But to my understanding now, looks like we need to export the file to a certain location, maybe a call to upload to a static location within the application, maybe s3 buckets in future.

So here, i my task now would be.

1. Create a way to save to a static location locally. This could enable for us to just provide the file through a publicly accessible route.
2. I guess the current approach taken from me is not viable since people needs to understand how to expose an api from their end as well.

**Comment by Mansh05** [comment]
Understood on the obfuscated as well.

**Comment by weex** [comment]
Yes, being able to save locally means no additional servers or machinery needed. We could have automation with just this. It's up to you if you want to leave the POST in. My bias would be toward removing it so there's one fewer things to support and later it can be added if needed to solve some other problem that may arise.

**Comment by weex** [comment]
I suggested /public/moderation/blocklist.csv since /public is already served, moderation could be a new folder just for purposes of supporting scalable moderation and giving it a single csv name means one only needs a domain name to have an idea from where to grab its blocklist (if available).

**Comment by Mansh05** [comment]
@weex done.

**Pull request merged**
