### PR TITLE
[WIP] Makary go/issue405 

### LINKED ISSUE #405: Problem: Static pages still use the Mastodon logo
Use file list from #245 to replace old branding on the static pages (error pages, about, rules, etc.)

### PR DESCRIPTION
**Pull request by MakaryGo**
Should fix #405, at the moment work in progress.

### CODE REVIEW

**Comment by MakaryGo** [comment]
Should now display new logo in following places:
- static pages (/about, /explore, etc.)
    -  footer area:
image

    - header 
image

**Comment by weex** [comment]
> Should now display new logo in following places:

Ok, thanks. I'll check it out and if it looks good merge it.

**Comment by MakaryGo** [comment]
> Ok, thanks. I'll check it out and if it looks good merge it.

Please don't; it only partially solves the issue, but before I proceed I need tests :)

**Comment by weex** [comment]
Screen Shot 2022-02-22 at 9 48 43 AM
Screen Shot 2022-02-22 at 9 48 39 AM

**Comment by MakaryGo** [comment]
@weex pretty nice! Could you maybe test it with some light theme as well?

**Comment by MakaryGo** [comment]
And the footer?

**Comment by weex** [comment]
> And the footer?
Screen Shot 2022-02-22 at 10 01 15 AM

**Comment by MakaryGo** [comment]
> > And the footer?
> 
> Screen Shot 2022-02-22 at 10 01 15 AM

That actually worked out as expected :)

**Comment by weex** [comment]
Interesting that this got merged as well, were both from the same branch?

**Comment by MakaryGo** [comment]
Apparently so, I'm sorry, I was doing a lot of branching lately ;)
I'll just open a new Problem for next UI task

**Comment by weex** [comment]
Yeah, git gives no warning when branching from WIP. Sounds like a plan!

**Pull request merged**
