### PR TITLE
fix: add copy command early to get gems into the container

### PR DESCRIPTION
**Pull request by Mansh05**
Fix the docker build.

### CODE REVIEW

**Comment by weex** [comment]
May fix #306

**Comment by weex** [comment]
I'm stumped by this CI error. Thoughts?

**Comment by Mansh05** [comment]
Looking into it @weex, will try to figure out the issue here.

**Comment by Mansh05** [comment]
sorry for the delay

**Comment by weex** [comment]
Submitted a ticket to Deepsource since I don't see how this is caused by us. Going to proceed without it and see if docker will build.

**Pull request merged**
